export const MAX_PAGE_SIZE = 100;

export const cardsHousesDefault = [
  {
    id: '1',
    typeHouse: 'bungalow',
    price: '25000',
    rooms: '2',
    country: 'Belarus',
    name: 'Yauheni Zakharenka',
    buildDate: '02.07.2021',
    salesman: true,
  },
  {
    id: '2',
    typeHouse: 'country house',
    price: '145000',
    rooms: '6',
    country: 'Belarus',
    name: 'Maurice Brooks',
    buildDate: '12.05.2021',
    salesman: false,
  },
  {
    id: '3',
    typeHouse: 'Terraced house',
    price: '55000',
    rooms: '2',
    country: 'Belarus',
    name: 'Clinton Cook',
    buildDate: '02.07.2021',
    salesman: true,
  },
  {
    id: '4',
    typeHouse: 'Block of flats',
    price: '150500',
    rooms: '3',
    country: 'Belarus',
    name: 'Kerry McBride',
    buildDate: '02.07.2021',
    salesman: true,
  },
  {
    id: '5',
    typeHouse: 'villa',
    price: '3000000',
    rooms: '8',
    country: 'Spain',
    name: 'Karina Bertosh',
    buildDate: '19.08.2021',
    salesman: true,
  },
  {
    id: '6',
    typeHouse: 'cottage',
    price: '250000',
    rooms: '4',
    country: 'Belarus',
    name: 'Simon West',
    buildDate: '02.07.2021',
    salesman: false,
  },
  {
    id: '7',
    typeHouse: 'weather-board house',
    price: '1500000',
    rooms: '6',
    country: 'Belarus',
    name: 'Emil McCoy',
    buildDate: '02.07.2021',
    salesman: true,
  },
  {
    id: '8',
    typeHouse: 'Mansion',
    price: '5000000',
    rooms: '27',
    country: 'Belarus',
    name: 'Dylan Garrison',
    buildDate: '02.07.2021',
    salesman: false,
  },
];
