export const cardsHouses = [
  {
    id: 1,
    typeHouse: 'A bungalow',
    image: 'img/Abungalow.jpg',
    price: 25000,
    rooms: 2,
    country: 'Belarus',
    city: 'Polotsk',
    author: 'Yauheni Zakharenka',
    addDate: '02.07.2021',
    likes: 17,
    views: 145,
  },
  {
    id: 2,
    typeHouse: 'A country house',
    image: 'img/Acountryhouse.jpg',
    price: 145000,
    rooms: 6,
    country: 'Belarus',
    city: 'Polock',
    author: 'Maurice Brooks',
    addDate: '12.05.2021',
    likes: 25,
    views: 455,
  },
  {
    id: 3,
    typeHouse: 'A Terraced house',
    image: 'img/Terracedhouse.jpg',
    price: 55000,
    rooms: 2,
    country: 'Belarus',
    city: 'Polock',
    author: 'Clinton Cook',
    addDate: '02.07.2021',
    likes: 12,
    views: 635,
  },
  {
    id: 4,
    typeHouse: 'Block of flats',
    image: 'img/Blockofflats2.jpg',
    price: 150500,
    rooms: 3,
    country: 'Belarus',
    city: 'Polock',
    author: 'Kerry McBride',
    addDate: '02.07.2021',
    likes: 25,
    views: 785,
  },
  {
    id: 5,
    typeHouse: 'A villa',
    image: 'img/Villa.jpg',
    price: 3000000,
    rooms: 8,
    country: 'Spain',
    city: 'palma de Mallorca',
    author: 'Karina Bertosh',
    addDate: '19.08.2021',
    likes: 995,
    views: 5123,
  },
  {
    id: 6,
    typeHouse: 'A cottage',
    image: 'img/Acottage.jpg',
    price: 250000,
    rooms: 4,
    country: 'Belarus',
    city: 'Polock',
    author: 'Simon West',
    addDate: '02.07.2021',
    likes: 85,
    views: 845,
  },
  {
    id: 7,
    typeHouse: 'A weather-board house',
    image: 'img/Aweather-boardhouse.jpg',
    price: 1500000,
    rooms: 6,
    country: 'Belarus',
    city: 'Polock',
    author: 'Emil McCoy',
    addDate: '02.07.2021',
    likes: 2,
    views: 15,
  },
  {
    id: 8,
    typeHouse: 'Mansion',
    image: 'img/Mansion.jpg',
    price: 5000000,
    rooms: 27,
    country: 'Belarus',
    city: 'Minsk',
    author: 'Dylan Garrison',
    addDate: '02.07.2021',
    likes: 566,
    views: 855,
  },
];
